---
title: "Replicating Postpass examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Replicating Postpass exampls}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidypass)
```

```{r}
bbox <- st_as_sfc(st_bbox(c(
  xmin = 8.34,
  xmax = 8.46,
  ymin = 48.97,
  ymax = 49.03
)))

pp_tbl("point") |>
  filter(tags %->>% 'amenity' == "fast_food" & geom %&&% !!pg_bbox(bbox)) |>
  transmute(name = tags %->>% 'name', geom) |>
  collect()
```

```{r}
# BAD
point_sql <- pp_tbl("point") |>
  filter(tags %->>% 'amenity' == "fast_food" & geom %&&% !!pg_bbox(bbox)) |>
  transmute(name = tags %->>% 'name', geom)

poly_sql <- pp_tbl("polygon") |>
  filter(tags %->>% 'amenity' == "fast_food" & geom %&&% !!pg_bbox(bbox)) |>
  transmute(name = tags %->>% 'name', geom)

union(point_sql, poly_sql) |>
  collect()
```


```{r}
# Better!
pp_tbl("pointpolygon") |>
  filter(tags %->>% 'amenity' == "fast_food" & geom %&&% !!pg_bbox(bbox)) |>
  transmute(name = tags %->>% 'name', geom) |>
  collect()
```

```{r}
pp_tbl("point") |>
  unwrap(tags %->>% c("amenity", "cuisine")) |>
  filter(amenity == "fast_food" & geom %&&% !!pg_bbox(bbox)) |>
  group_by(cuisine) |>
  summarise(cuisine = cuisine, count = n()) |>
  arrange(desc(count)) |>
  collect(geojson = FALSE)
```


```{r}
pp_tbl("point") |>
  unwrap(tags %->>% c("amenity", "cuisine")) |>
  mutate(cuisine = regexp_split_to_table(tags %->>% 'cuisine', ";")) |>
  filter(amenity == "fast_food" & geom %&&% !!pg_bbox(bbox)) |>
  group_by(cuisine) |>
  summarise(cuisine = cuisine, count = n()) |>
  arrange(desc(count)) |>
  collect(geojson = FALSE)
```



```{r}
pp_tbl("line") |>
  unwrap(tags %->>% c("name", "route", "ref")) |>
  filter(route == "tram" & ref == "3" & geom %&&% !!pg_bbox(bbox)) |>
  select(name, geom) |>
  collect()
```


```{r}
pp_tbl("pointpolygon") |>
  filter(
    tags %?% 'addr:street' &
    !tags %?% 'addr:postcode' &
    geom %&&% !!pg_bbox(bbox)) |>
  select(osm_id, geom) |>
  collect()
```

```{r}
pp_tbl("point") |>
  filter(tags %->>% "ref" == "15398") |>
  select(osm_id, geom) |>
  collect()

pp_tbl("polygon") |>
  unwrap(tags %->>% c("name", "boundary")) |>
  filter(name == "München" & boundary == "administrative") |>
  select(osm_id, geom) |>
  collect()
```


```{r}
bbox <- st_as_sfc(st_bbox(c(
  xmin = 5.53,
  xmax = 47.23,
  ymin = 15.38,
  ymax = 54.96
)))

points <- pp_tbl("point")
polys <- pp_tbl("polygon")

points |>
  cross_join(polys) |>
  filter(
    way.y %&&% !!pg_bbox(bbox) &
    st_contains(way.y, way.x) &
    tags.x %->% 'addr:postcode' %<>% tags.y %->% 'postal_code'
  ) |>
  mutate(
    punkt_plz = tags.x %->% 'addr:postcode',
    poly_plz = tags.y %->% 'postal_code'
  ) |>
  select(
    osm_id = osm_id.x,
    way = way.x,
    punkt_plz,
    poly_plz
  )
```


```{r}
pp_tbl("polygon") |>
  cross_join(pp_tbl("polygon")) |>
  filter(
    osm_id.x < osm_id.y,
    way.x %&&% !!pg_bbox(bbox),
    way.y %&&% !!pg_bbox(bbox),
    !is.na(landuse.x),
    !is.na(landuse.y),
    st_overlaps(way.x, way.y)
  ) |>
  mutate(inter = st_intersection(way.x, way.y)) |>
  select(inter, landuse1 = landuse.x, landuse2 = landuse.y) |>
  collect()
```
